import {React,useState} from 'react'
import {View,Text,TouchableOpacity, ScrollView, FlatList,ActivityIndicator,StatusBar} from 'react-native'
import NewsItem from '../components/NewsItem'
export default function News({navigation}) {
    const [data,setData] = useState([
      {
          "title": "Everything We Know About the Samsung Galaxy S23",
          "author": "Andrew Lanxon",
          "published_date": "2023-01-14 17:45:00",
          "published_date_precision": "timezone unknown",
          "link": "http://www.msn.com/en-us/news/technology/everything-we-know-about-the-samsung-galaxy-s23/ar-AA15BlgW",
          "clean_url": "msn.com",
          "excerpt": "The S23 is expected to be announced at Samsung's next Unpacked event.",
          "summary": "It's almost February, which means it's time to turn our attention to what's next for Samsung. The company just announced its next Unpacked event will take place on Feb. 1, and the Galaxy S23 lineup is expected to be the star of the show.\nThe Samsung Galaxy S22 range includes some of our top phones from 2022. The base S22 impressed as a more affordable option, the S22 Plus is a superb all-rounder while the all-powerful S22 Ultra blew us away with its stellar camera skills. We even gave the Plus and Ultra CNET Editors' Choice Awards.",
          "rights": "msn.com",
          "rank": 100,
          "topic": "tech",
          "country": "US",
          "language": "en",
          "authors": "Andrew Lanxon",
          "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA15Bsk7.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
          "is_opinion": false,
          "twitter_account": null,
          "_score": 26.351477,
          "_id": "5b1d6b8784cb3baf0f3a98fa10ea8806"
        },
      {
        "title": "Apple Should Bring These Features to the iPhone 15",
        "author": "Lisa Eadicicco",
        "published_date": "2023-01-18 14:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/apple-should-bring-these-features-to-the-iphone-15/ar-AA13V2Ly",
        "clean_url": "msn.com",
        "excerpt": "Commentary: USB-C charging, Touch ID and more uses for the Dynamic Island are on my wish list.",
        "summary": "With the iPhone 14 Pro and Pro Max, Apple gave us many of the features we've been waiting for. These include an always-on display and better multitasking thanks to Apple's Dynamic Island. But there are a few ways Apple could take things further with the iPhone 15.\nFor example, the company could do a better job of bringing certain Pro-exclusive features down to its less-expensive iPhone models. Samsung frequently does this with its cheaper phones, and I'd like to see Apple embrace this approach more fully, too.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Lisa Eadicicco",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA13c9uA.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 12.424223,
        "_id": "ca4a63d6ef226a9959ff79905fffe962"
      },
      {
          "title": "Samsung Galaxy S23 Needs These Features",
          "author": "Lisa Eadicicco",
          "published_date": "2023-01-14 18:00:00",
          "published_date_precision": "timezone unknown",
          "link": "http://www.msn.com/en-us/news/technology/samsung-galaxy-s23-needs-these-features/ar-AA13GEan",
          "clean_url": "msn.com",
          "excerpt": "Commentary: Samsung should improve on some of the flagship phone's basics.",
          "summary": "Samsung's Galaxy S22 features a fresh design and an upgraded camera that's better at seeing in the dark. But there's plenty of room for Samsung to further upgrade with the Galaxy S23, expected to arrive in February.\nIn particular, I'd like to see longer-lasting batteries, more photographic features that take advantage of the Galaxy S family's impressive cameras and faster charging that doesn't require an expensive adapter.\nSamsung typically releases new Galaxy S devices in the first couple of months of the year, and it will likely maintain that schedule in 2023.",
          "rights": "msn.com",
          "rank": 100,
          "topic": "tech",
          "country": "US",
          "language": "en",
          "authors": "Lisa Eadicicco",
          "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16e85d.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
          "is_opinion": false,
          "twitter_account": null,
          "_score": 24.413496,
          "_id": "03987be384d7376ed775dcbcdc672494"
        },
      {
        "title": "Your iPhone Has a One-Handed Keyboard. Here's How to Unlock It",
        "author": "Sareena Dayaram",
        "published_date": "2023-01-15 19:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/your-iphone-has-a-one-handed-keyboard-here-s-how-to-unlock-it/ar-AA16g9Tb",
        "clean_url": "msn.com",
        "excerpt": "Can you type on your iPhone with one hand? This setting change makes it way easier.",
        "summary": "Big iPhones are here to stay. Apple has continued to size-up its iconic phone since it launched the original 3.5-inch iPhone in 2007. Now, the iPhone 14 Pro Max is nearly double that size, spanning a whopping 6.7 inches. Using an iPhone with a sprawling display makes for a solid experience, especially when watching Netflix or reading the news. But large screens have their trade-offs: For one thing, it's much harder to type on them without using both hands.\nIf you're having trouble typing out your thoughts single-handedly, there's a one-handed iPhone keyboard you can access quicker than you think.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Sareena Dayaram",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16a8Ml.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 11.835233,
        "_id": "74bf2119ccbc0677555532ba0d7decfd"
      },
      {
        "title": "Make One-Handed Typing Easier on iPhone by Changing This One Setting",
        "author": "Sareena Dayaram",
        "published_date": "2023-01-14 20:30:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/make-one-handed-typing-easier-on-iphone-by-changing-this-one-setting/ar-AA16g9Tb",
        "clean_url": "msn.com",
        "excerpt": "Apple has a quick fix for anyone who wants to use one hand to type.",
        "summary": "It's no secret that big iPhones are here to stay. Apple's iconic product has physically grown since its launch, from the compact 3.5-inch screen on the original iPhone to the supersized 6.7-inch one on the iPhone 14 Pro Max. Using an iPhone with a sprawling display makes for a solid experience, especially when watching videos or reading the news. But large screens have their tradeoffs: For one thing, it's much harder to type on them without using both hands.\nIf you're having trouble typing out your thoughts single-handedly, there's a one-handed iPhone keyboard you can access quicker than you think.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Sareena Dayaram",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16a8Ml.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 11.815165,
        "_id": "230ea1430c464bfc9a796ad17518cc8e"
      },
      {
        "title": "Pixel 7 vs. iPhone 14 vs. Galaxy S22: The Big Three Phones of 2022 Compared",
        "author": "Sareena Dayaram",
        "published_date": "2023-01-16 14:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/pixel-7-vs-iphone-14-vs-galaxy-s22-the-big-three-phones-of-2022-compared/ar-AA12GvUp",
        "clean_url": "msn.com",
        "excerpt": "Samsung, Apple, and Google's flagship offerings set the bar for phones in 2022. Here's how they compare, spec by spec.",
        "summary": "The big three flagship phones for 2022 were unveiled across last year, kicking off with Samsung's offering, followed by Apple in September and finally Google. Each of the three phones received good reviews, but figuring out which is right for you can be complicated.\nThe $599 (£599, AU$999) Pixel 7 is Google's latest flagship, built to compete with established phone leaders like Apple's iPhone 14 and Samsung's Galaxy S22. New to the Pixel 7 is the Tensor G2 processor, a camera with improved zoom, face unlock and updated design.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Sareena Dayaram",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA14vkhX.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 11.551315,
        "_id": "6ff205eb6502854fab76ccfc143c7934"
      },
      {
        "title": "AirDrop Is Like FedEx for Your iPhone Files and Photos. Here's How to Use It",
        "author": "Patrick Holland",
        "published_date": "2023-01-14 11:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/airdrop-is-like-fedex-for-your-iphone-files-and-photos-here-s-how-to-use-it/ar-AAREc6e",
        "clean_url": "msn.com",
        "excerpt": "AirDrop is perhaps one of Apple's best features. If you're not using it yet, you're missing out.",
        "summary": "If you're still emailing photos from your iPhone to nearby friends or are still using a USB thumb drive to transfer a few files from your Mac, stop. Try AirDrop instead. Whether you have an iPhone 14, an iPad Mini or a new M2 MacBook Pro, AirDrop is a convenient way to transfer files and content from one Apple device to another. AirDrop lets you share photos, documents, videos, audio recordings, contact cards, web links and notes (among other things) quickly between Apple devices.\nAirDrop is limited to iOS and MacOS.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Control Center,Patrick Holland",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA15odRF.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 11.39913,
        "_id": "2ccd1bc35e24f5bd8e7a7b185763ad19"
      },
      {
        "title": "Apple addressing iPhone 14 issue with software update: Reports",
        "author": "Julia Musto",
        "published_date": "2023-01-20 20:30:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/apple-addressing-iphone-14-issue-with-software-update-reports/ar-AA16zFGz",
        "clean_url": "msn.com",
        "excerpt": "Apple is reportedly releasing a new update that will address a problem with some iPhone 14 Pro and Pro Max models, with the iOS 16.3 Release Candidate now available.",
        "summary": "Apple is reportedly releasing a new software update that will address an issue that causes horizontal lines to flash across the displays of some iPhone 14 Pro and Pro Max models.\nSara Carter goes on-the-ground in Philadelphia's most drug-addled precincts\nBiden names Ron Klain as chief of staff\nPerino: The White House is letting Karine Jean-Pierre twist in the wind\nEvidence in college admissions scandal shows email between Rick Singer, Lori Loughlin and Mossimo Giannulli\nCollege consultant: What R",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Julia Musto",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16zIih.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 11.237964,
        "_id": "c3af9ccf4573cb8e9904154dc1fdd494"
      },
      {
        "title": "iOS 16 Makes Your iPhone Way More Powerful Than You Think",
        "author": "Read more:",
        "published_date": "2023-01-19 14:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/ios-16-makes-your-iphone-way-more-powerful-than-you-think/ar-AAZDuIq",
        "clean_url": "msn.com",
        "excerpt": "Why isn't Apple shouting these hidden features from the rooftop?",
        "summary": "You already know your iPhone can do a lot, but with any version of iOS 16 installed, it's more powerful than you think. Underneath all the major new features, like home screen widgets, Live Activities and Emergency SOS via satellite, there are impressive tools and settings that Apple may not give as much shine to, but that can help make your day-to-day more efficient, interesting and fun.\nI'm going to walk you through what to know about the best hidden gems in iOS 16, like password-protected photo albums and easily accessible Wi-Fi passwords.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Nelson Aguilar,Read more:",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA12p1eF.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 11.191781,
        "_id": "eb6551ba18b0a14d1e41f7d95ec87493"
      },
      {
        "title": "iOS 16.3 Beta 2: All the New Features That Could Hit Your iPhone",
        "author": "More",
        "published_date": "2023-01-16 12:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/ios-16-3-beta-2-all-the-new-features-that-could-hit-your-iphone/ar-AA160olL",
        "clean_url": "msn.com",
        "excerpt": "It's unclear when the update will go live.",
        "summary": "Apple has released the iOS 16.3 beta 2 to public beta testers, bringing new features like help finding parking via Apple Maps. The first iOS 16.3 beta appeared shortly after the release of iOS 16.2 and brought a few new features to testers' iPhones as well.\nAs always, we recommend downloading a beta only on something other than your primary device. Since these are beta versions of iOS 16.3, the features might be buggy and your device's battery life may be shortened, so it's best to keep betas on a secondary device.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "More,Zachary McAuliffe",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA160qJm.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.93096,
        "_id": "3aa8ff4eb8e40f04d7c1f3d684dfd91c"
      },
      {
        "title": "2023 New Phones: The Best Coming From Samsung, Apple, Google and More",
        "author": "Lisa Eadicicco",
        "published_date": "2023-01-14 18:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/2023-new-phones-the-best-coming-from-samsung-apple-google-and-more/ar-AA15b5U7",
        "clean_url": "msn.com",
        "excerpt": "From the Samsung Galaxy S23 to the Google Pixel 7A, these are the phones we're most looking forward to seeing this year.",
        "summary": "The year has just begun, but we're already expecting several new phones from companies like Samsung and OnePlus to arrive in a matter of weeks. Though it's hard to predict exactly what's in store for the smartphone industry in 2023, it's possible to make some educated guesses, since companies like Apple, Google and Samsung mostly stick to the same launch routine each year.\nThe iPhone 15 lineup, for example, is expected to arrive in September -- possibly with USB-C charging for the first time. The Galaxy S23 will likely be one of the first new phones we see in 2023, considering the tech giant is holding an Unpacked event on Feb.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Lisa Eadicicco,What we're expecting:",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA15brPb.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.873761,
        "_id": "5be576357cce2c7402a9ecb1cac82477"
      },
      {
        "title": "Half of all iPhones could be made in India by 2027; Chinese suppliers already feeling effects.",
        "author": "/u/SUPRVLLAN",
        "published_date": "2023-01-16 20:08:58",
        "published_date_precision": "full",
        "link": "https://www.reddit.com/r/technology/comments/10dpzex/half_of_all_iphones_could_be_made_in_india_by",
        "clean_url": "reddit.com",
        "excerpt": "454 votes, 45 comments. 13.6m members in the technology community. Subreddit dedicated to the news and discussions about the creation and use of …",
        "summary": "Subreddit dedicated to the news and discussions about the creation and use of technology and its surrounding issues.",
        "rights": "reddit.com",
        "rank": 39,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "/u/SUPRVLLAN",
        "media": "https://external-preview.redd.it/ZwkNtNMs4NFoFuQyGuBi1T8k58SRcdTHIU-dPJDxv1s.jpg?auto=webp&v=enabled&s=5ae51c08e86686921581b3b64ad0050f5acfa8fa",
        "is_opinion": false,
        "twitter_account": "@reddit",
        "_score": 9.998164,
        "_id": "62de07e50cc05f30281010dd20c0516a"
      },
      {
        "title": "The Apple TV expects you to have an iPhone in order to accept new iCloud terms and conditions : technology",
        "author": "/u/pobody-snerfect",
        "published_date": "2023-01-17 00:57:45",
        "published_date_precision": "full",
        "link": "https://www.reddit.com/r/technology/comments/10dy7zd/the_apple_tv_expects_you_to_have_an_iphone_in",
        "clean_url": "reddit.com",
        "excerpt": "0 votes and 33 comments so far on Reddit",
        "summary": "Subreddit dedicated to the news and discussions about the creation and use of technology and its surrounding issues.",
        "rights": "reddit.com",
        "rank": 39,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "/u/pobody-snerfect",
        "media": "https://external-preview.redd.it/dba5W5jWJ6SujEKUSztwFuJUfFnDGdqK4C4TztmX7dE.jpg?auto=webp&v=enabled&s=e51a4e3fd6c76dc29d6b4c854284e519a37efa26",
        "is_opinion": false,
        "twitter_account": "@reddit",
        "_score": 9.966663,
        "_id": "2e97e75ee8c18808d0e7d5c393d87511"
      },
      {
        "title": "Android is Closing the Gap With Apple With This New Feature",
        "author": "Lisa Eadicicco",
        "published_date": "2023-01-14 20:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/android-is-closing-the-gap-with-apple-with-this-new-feature/ar-AA1610Sp",
        "clean_url": "msn.com",
        "excerpt": "Jumping devices is about to get a lot easier on Android.",
        "summary": "Google is launching another new feature to make switching between all the Android devices in your life a little easier. Media Notifications, announced at CES, will let you transition audio content from the car to your phone, headphones, phone and smart home devices based on proximity. It's Google's newest effort to bring its Android ecosystem up to par with Apple's when it comes to connectivity and cohesiveness between devices.\nThe way Apple's products seamlessly connect to one another has helped it become the world's second-largest smartphone maker and the top seller of smartwatches and wireless earbuds.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Lisa Eadicicco",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA160ZFj.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 8.294446,
        "_id": "6159b12a76677e03593ff1a0d608dbaf"
      },
      {
        "title": "Galaxy S23 Ultra's Secret Weapon Could Be This New Samsung Chip",
        "author": "Stephen Shankland",
        "published_date": "2023-01-17 03:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/galaxy-s23-ultra-s-secret-weapon-could-be-this-new-samsung-chip/ar-AA16pnD3",
        "clean_url": "msn.com",
        "excerpt": "Exclusive: Samsung's Isocell HP2 image sensor can shoot photos at 12.5, 50 or even 200 megapixels thanks to new pixel binning options.",
        "summary": "With its new 200-megapixel Isocell HP2 image sensor, Samsung will try to give smartphone photographers the best of both worlds: high resolution and good image quality in challenging conditions.\nSamsung Electronics' Isocell HP2 image sensor can take photos at 200, 50, or 12.5 megapixel resolution and adds new HDR tricks.\nThe HP2 is in mass production. Samsung has neither announced its shipment date nor confirmed which phone it will arrive in. Still, the sensor is expected to power the main camera on the company's flagship Galaxy S23 Ultra phone, likely to debut Feb.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Stephen Shankland",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16qdPo.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 7.994442,
        "_id": "535aca7ad5107d2de31d9fe37875e73a"
      },
      {
        "title": "Galaxy S23 Ultra's Secret Weapon Could Be This Samsung Camera Chip",
        "author": "Stephen Shankland",
        "published_date": "2023-01-18 17:15:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/galaxy-s23-ultra-s-secret-weapon-could-be-this-samsung-camera-chip/ar-AA16pnD3",
        "clean_url": "msn.com",
        "excerpt": "Exclusive: Samsung's Isocell HP2 image sensor can shoot photos at 12.5, 50 or even 200 megapixels thanks to more efficient light-gathering technology.",
        "summary": "With its new Isocell HP2 image sensor, Samsung will try giving smartphone photographers the best of both worlds: a high  200-megapixel resolution and good image quality in challenging conditions.\nThe HP2 is in mass production, but Samsung hasn't confirmed which phone it'll arrive in. The sensor is expected to power the main camera on the company's flagship Galaxy S23 Ultra phone, though, which likely will debut at a Feb. 1 Samsung event.\nLoad Error\nImage sensor designers face a tradeoff. Increasing resolution means each pixel on the sensor is smaller, and for a given technology, smaller pixels aren't able to gather light as well.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "2:48 p.m.:,Correction,Stephen Shankland",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16qdPo.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 7.8110313,
        "_id": "6e164277327af6188f649cd44f13be6c"
      },
      {
        "title": "Apple HomePod Speaker Upgrades Sound for $299: Hands-On",
        "author": "Ty Pendlebury",
        "published_date": "2023-01-18 21:30:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/apple-homepod-speaker-upgrades-sound-for-299-hands-on/ar-AA16tRjW",
        "clean_url": "msn.com",
        "excerpt": "The new full-size smart speaker can also sense room temperature and listen for smoke alarms.",
        "summary": "Apple announced its second-generation HomePod on Wednesday at an event in New York City, almost two years after it discontinued the first HomePod. I was on hand at the company's loft in Tribeca to hear the second-gen speaker for myself.\nSo, first off, what's changed? The new version is a full-size smart speaker with \"improved acoustics\" and smart-home capabilities, including temperature and humidity sensors as well as the ability to notify you if it hears a smoke or carbon monoxide alarm. Both the new HomePod and the existing HomePod Mini rely on Siri, the company's voice assistant, to listen for and execute \"Hey, Siri\" commands.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Ty Pendlebury",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16twBG.img?h=315&w=600&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 7.240975,
        "_id": "339a1274721815b45011f36ecc8f807e"
      },
      {
        "title": "Google is planning on making its own Apple Air Tags called Grogu using Ultra-wideband Bluetooth",
        "author": "Mehul Reuben Das",
        "published_date": "2023-01-17 12:21:49",
        "published_date_precision": "full",
        "link": "https://www.msn.com/en-in/lifestyle/shopping/google-is-planning-on-making-its-own-apple-air-tags-called-grogu-using-ultra-wideband-bluetooth/ar-AA16qSns?li=BBnb2gh",
        "clean_url": "msn.com",
        "excerpt": "Google is planning on making its own Apple Air Tags called Grogu using Ultra-wideband Bluetooth",
        "summary": "Google is developing a new Bluetooth tracking device that will take on Apple's AirTag. Ultra-wideband (UWB) connection has been a feature of Google's premium 'Pro' phones since 2021, including the Pixel 6 Pro and Pixel 7 Pro. Although the hardware has so far only been applied in specialised situations like transmitting data to a buddy or unlocking a luxury automobile, it is evident that Google wants to see UWB utilised more frequently.\nGoogle was developing a new Nest speaker that will support UWB and allow for rapid audio transfers by positioning your Pixel close to the speaker.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Firstpost,Mehul Reuben Das",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16qSne.img?h=315&w=600&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 7.1665154,
        "_id": "a8e5f783121ec8dd7c20a364d692ccc2"
      },
      {
        "title": "Intel CEO: Chip supply chains will shape geopolitics more than oil over the next 50 years",
        "author": "Clare Duffy",
        "published_date": "2023-01-17 17:30:52",
        "published_date_precision": "full",
        "link": "https://www.cnn.com/2023/01/17/tech/intel-ceo-chip-manufacturing-davos/index.html",
        "clean_url": "cnn.com",
        "excerpt": "Global politics will be dominated by the availability, trade and investment in microchips for the next several decades, Intel CEO Pat Gelsinger told CNN Tuesday.",
        "summary": "New York CNN —\n\nGlobal politics will be dominated by the availability, trade and investment in microchips for the next several decades, Intel CEO Pat Gelsinger told CNN Tuesday.\n\nThe location of 'oil reserves [has] defined geopolitics for the last five decades,' Gelsinger said in an interview with CNN's Julia Chatterley at the World Economic Forum in Davos. 'Where the technology supply chains are, and where semiconductors are built, is more important for the next 5 decades.'\n\nGelsinger said the company's investment in new manufacturing facilities in the United States, Europe and elsewhere is important not only for the company's future, but for the 'globalization of the most critical resource to the future of the world.",
        "rights": "cnn.com",
        "rank": 61,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "CNN,Clare Duffy",
        "media": "https://media.cnn.com/api/v1/images/stellar/prod/230117110556-intel-chip-stock.jpg?c=16x9&q=w_800,c_fill",
        "is_opinion": false,
        "twitter_account": "@CNNbusiness",
        "_score": 6.743249,
        "_id": "39e67d056f8a4f229d9fb95e7f6eb549"
      },
      {
        "title": "Apple launches new MacBook Pro and Mac Mini",
        "author": "Lim Yian Lu",
        "published_date": "2023-01-20 02:30:53",
        "published_date_precision": "full",
        "link": "https://sg.style.yahoo.com/new-year-new-you-supercharge-your-productivity-with-the-new-mac-book-pro-and-mac-mini-023053078.html",
        "clean_url": "yahoo.com",
        "excerpt": "Apple announced the new 14- and 16-inch MacBook Pro featuring the all-new M2 Pro and M2 Max, and the new Mac mini, supercharged by M2 and M2 Pro.",
        "summary": "Apple announced the new 14- and 16-inch MacBook Pro featuring the all-new M2 Pro and M2 Max, and the new Mac mini, supercharged by M2 and M2 Pro on Tuesday (17 January).\nThe M2 Pro and M2 Max processing chips are Apple's next-generation pro silicon that brings even more power-efficient performance and battery life to pro users. The Apple M2 is the second generation of processing chips for Mac computers after their transition from Intel Core to Apple silicon.\nMacBook Pro with M2 Pro and M2 Max\nWith M2 Pro and M2 Max, the new MacBook Pro tackles demanding tasks with greater ease: effects rendering is up to six times faster than the fastest Intel-based MacBook Pro; colour grading is up to two times faster; image processing and rendering animations are up to 80 per cent faster; code compiling is up to two and a half times faster.",
        "rights": "yahoo.com",
        "rank": 31,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Lim Yian Lu",
        "media": "https://s.yimg.com/ny/api/res/1.2/AykHexXqbrCmiXelxln6xg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03NTA-/https://s.yimg.com/os/creatr-uploaded-images/2023-01/87934ed0-971c-11ed-beb6-da3d0e0a37b3",
        "is_opinion": false,
        "twitter_account": "@yahoosg",
        "_score": 6.7198615,
        "_id": "489c52bb64fd4e36fabb00e471ce3e6b"
      },
      {
        "title": "Samsung Galaxy S23 Needs These Features",
        "author": "Lisa Eadicicco",
        "published_date": "2023-01-14 18:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/samsung-galaxy-s23-needs-these-features/ar-AA13GEan",
        "clean_url": "msn.com",
        "excerpt": "Commentary: Samsung should improve on some of the flagship phone's basics.",
        "summary": "Samsung's Galaxy S22 features a fresh design and an upgraded camera that's better at seeing in the dark. But there's plenty of room for Samsung to further upgrade with the Galaxy S23, expected to arrive in February.\nIn particular, I'd like to see longer-lasting batteries, more photographic features that take advantage of the Galaxy S family's impressive cameras and faster charging that doesn't require an expensive adapter.\nSamsung typically releases new Galaxy S devices in the first couple of months of the year, and it will likely maintain that schedule in 2023.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Lisa Eadicicco",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16e85d.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 6.671788,
        "_id": "03987be384d7376ed775dcbcdc672494"
      },
      {
        "title": "Apple CEO Tim Cook's slow, steady leadership style may turn out to be the exact antidote to the carnage sweeping the tech sector",
        "author": "Rating:",
        "published_date": "2023-01-20 23:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/apple-ceo-tim-cook-s-slow-steady-leadership-style-may-turn-out-to-be-the-exact-antidote-to-the-carnage-sweeping-the-tech-sector/ar-AA16zV2Q",
        "clean_url": "msn.com",
        "excerpt": "Apple is now the only tech giant that hasn't had mass layoffs recently and analysts say it's due to CEO Tim Cook's more measured leadership.",
        "summary": "With Google's parent company Alphabet announcing layoffs Friday morning, Apple is now the only major tech giant that hasn't conducted mass layoffs in recent months as a souring economy looms over Silicon Valley.\nThe combination of rising interest rates and ongoing inflation have led to cooling customer demand and shrinking advertising budgets lead Amazon, Microsoft, and now Google to dramatically cut headcount in recent months. The tech giants hired like mad during the early pandemic years, but are now looking to rein in their spending.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Rating:",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16zZSy.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg&x=710&y=371",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 6.5789366,
        "_id": "92cc3b66472a80f4d0e8b3fd7d86c38d"
      },
      {
        "title": "Collection of voice data for profit raises privacy fears",
        "author": "FILE",
        "published_date": "2023-01-18 12:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/collection-of-voice-data-for-profit-raises-privacy-fears/ar-AA16tqzz",
        "clean_url": "msn.com",
        "excerpt": "Voice data holds more intimate information than users realize, advocates said.",
        "summary": "A customer-service center uses artificial intelligence to identify a caller's agitation, an insurance company scans voice data to flag illness and raise rates, a five-star restaurant denies a reservation over personal details revealed by the tone on the other end of the line.\nIdaho murders suspect may have rare visual snow disorder\n22 states on alert as storm moves east\n8 shot, 1 in critical condition in mass shooting at MLK Jr. Day event in Florida\nChevrolet unveils 1st hybrid Corvette\nProminent Iranian actress arrested after criticizing regime\nBy the Numbers: MLK Jr.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "FILE",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA16tnOi.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 4.167327,
        "_id": "e723cca338cdf253e6c9c1b569e43e83"
      },
      {
        "title": "Glitching the Olimex LPC-P1343",
        "author": "",
        "published_date": "2023-01-17 16:14:46",
        "published_date_precision": "full",
        "link": "https://grazfather.github.io/posts/2019-12-08-glitcher",
        "clean_url": "github.io",
        "excerpt": "Back in the summer I was lucky enough to finagle my boss into letting me take Dmitry Nedospasov (@nedos)'s hardware hacking training. In it I cut my teeth on using an FPGA to interface with target…",
        "summary": "Back in the summer I was lucky enough to finagle my boss into letting me take Dmitry Nedospasov (@nedos)'s hardware hacking training. In it I cut my teeth on using an FPGA to interface with target hardware. After implementing a UART we implemented a module that could parse part of Apple's OneWire, used to negotiate power exchange, among other things, with your iPhone over the lightning cable. Our ‘final project' was to build a UART-controllable glitcher, using it to try to glitch a development board.",
        "rights": "github.io",
        "rank": 52,
        "topic": "tech",
        "country": "IO",
        "language": "en",
        "authors": "",
        "media": "https://grazfather.github.io/assets/2019-12-08-glitching/glitcher_scope.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 3.0228539,
        "_id": "b2f1f95e61dc7c8b25d2fa965a636456"
      },
      {
        "title": "The Apple TV 4K will apparently only work if you have an iPhone or iPad",
        "author": "Dzamira Dzafri",
        "published_date": "2023-01-17 00:00:00",
        "published_date_precision": "date",
        "link": "https://soyacincau.com/2023/01/17/the-apple-tv-4k-will-apparently-only-work-if-you-have-an-iphone-or-ipad/",
        "clean_url": "soyacincau.com",
        "excerpt": "Apple TV's new update will only allow users to use an iOS device to read the new Terms and Conditions rather than read it on the television itself.",
        "summary": "The Apple TV 4K is actually a neat and sleek TV box by Apple, and it's meant to work by itself as a regular TV box—a vessel for your regular entertainment including Netflix, YouTube, Spotify, and other apps. But after a recent software update, tvOS expects users to have access to an iPhone or iPad to continue accessing it.\n\nTwitter user @hugelgupf reported the problem yesterday, on 16 January 2023. According to them, they do not own a single Apple device, but they own an Apple TV. However, every time they start the Apple TV, they get a prompt that states that agreeing to a new Terms and Conditions would require a device running iOS 16 or later, or iPadOS 16 or later.",
        "rights": "soyacincau.com",
        "rank": 48304,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Dzamira Dzafri",
        "media": "https://soyacincau.com/wp-content/uploads/2023/01/230117-apple-tv-4k-2022.jpg",
        "is_opinion": false,
        "twitter_account": "https://twitter.com/soya_cincau",
        "_score": 9.833739,
        "_id": "24a4448c9a314a930460753f61e016f8"
      },
      {
        "title": "Netflix released a \"more fluid, delightful and polished\" UI design for its iPhone app",
        "author": "Dzamira Dzafri",
        "published_date": "2023-01-17 00:00:00",
        "published_date_precision": "date",
        "link": "https://soyacincau.com/2023/01/17/netflix-released-a-more-fluid-delightful-and-polished-ui-design-for-its-iphone-app/",
        "clean_url": "soyacincau.com",
        "excerpt": "The new changes for the Netflix app include a \"new billboard layout\" that \"responds as you move your device, with a subtle lighting effect\".",
        "summary": "— Janum Trivedi (@jmtrivedi) January 16, 2023 'This last year, I've been leading a UI refresh to make Netflix feel more fluid, delightful, and polished. Today, all that work shipped!' wrote Trivedi, who now works at Browser Company.\nAccording to Trivedi, the new changes for the app include a 'new billboard layout' that 'responds as you move your device, with a subtle lighting effect'. Changes also include 'wallpaper gradients that are created on-the-fly', a 'new card transition that's fully interruptible/interactive', 'new launch/profile animations' and 'more'.",
        "rights": "soyacincau.com",
        "rank": 48304,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Dzamira Dzafri",
        "media": "https://soyacincau.com/wp-content/uploads/2023/01/230117-netflix-redesign-scaled.jpg",
        "is_opinion": false,
        "twitter_account": "https://twitter.com/soya_cincau",
        "_score": 9.309112,
        "_id": "7734d597813ec916a382526cb6628986"
      },
      {
        "title": "Tech Review – CASEKOO Mag Clear Case for iPhone 14 pro – jim o brien",
        "author": "Deidre Richardson",
        "published_date": "2023-01-20 00:00:00",
        "published_date_precision": "date",
        "link": "https://www.inferse.com/411953/tech-review-casekoo-mag-clear-case-for-iphone-14-pro-jim-o-brien/",
        "clean_url": "inferse.com",
        "excerpt": "techbuzzirelandIreland's Leading real hands on tech review site and top YouTube tech review channel and the latest tech newsThe CASEKOO mag clear case is",
        "summary": "techbuzzirelandIreland's Leading real hands on tech review site and top YouTube tech review channel and the latest tech newsThe CASEKOO mag clear case is a nice clear case which is one of many options available from the brand, however this company offers some more for your more for money and is aimed at the younger owners perhaps as with your purchase you get two sets of Pandakoo stickers thrown in which I have not seen before with any case manufacturer so this could be something you could look at or if you are passing down the phone later on to one of your kids.",
        "rights": "inferse.com",
        "rank": 666805,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "B.A,Deidre Richardson,History Music,Lg Nexus On A Regular Basis.,Mobile Gadgets. A Graduate,Tablets",
        "media": "https://www.inferse.com/wp-content/uploads/2022/03/pexels-pixabay-259132.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 8.577915,
        "_id": "324c849a08eba9bbbf72a634fde989d9"
      },
      {
        "title": "Apple delays augmented reality glasses",
        "author": "Bloomberg",
        "published_date": "2023-01-18 00:00:00",
        "published_date_precision": "date",
        "link": "https://mybroadband.co.za/news/gadgets/476779-apple-delays-augmented-reality-glasses.html",
        "clean_url": "mybroadband.co.za",
        "excerpt": "The company is betting that AR and VR devices could be a major moneymaker, but the technical challenges of producing a consumer-friendly product has bedevilled much of the tech world.",
        "summary": "Apple Inc. is still planning to unveil its first mixed-reality headset this year, but an even more important follow-up product — lightweight augmented-reality glasses — has been postponed due to technical challenges.\n\nThe company had originally hoped to release the AR glasses after the debut of its mixed-reality headset, which combines both AR and virtual reality, but that part of the plan is now on hold.\n\nInstead, Apple will follow up with a lower-cost version of the mixed-reality headset as soon as 2024 or early 2025, according to people familiar with the deliberations.",
        "rights": "mybroadband.co.za",
        "rank": 11662,
        "topic": "tech",
        "country": "ZA",
        "language": "en",
        "authors": "Bloomberg",
        "media": "https://mybroadband.co.za/news/wp-content/uploads/2023/01/Apple-AR-glasses-concept-headline.jpg",
        "is_opinion": false,
        "twitter_account": "@mybroadband",
        "_score": 7.2935143,
        "_id": "de8a6e1b29bbb2d86592515d03314d0c"
      },
      {
        "title": "iPhone 15 prices LEAK! Base variants price listed here; BIG worry for Pro buyers",
        "author": "HT Tech",
        "published_date": "2023-01-17 06:52:08",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/iphone-15-prices-leak-base-variants-price-listed-here-big-worry-for-pro-buyers-71673938081597.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "The iPhone 15 leaked prices point at a big difference between standard and Pro variants. Here is why.",
        "summary": "The iPhone 15 leaked prices point at a big difference between standard and Pro variants. Here is why.\n The iPhone 15 is coming to us just as the Sun starts to set in 2023 and already, there is a worrying leak. We have got our hands on the possible prices of the iPhone 15 and based on that, it seems that the Pro variants could see a huge price hike this year. Not a new thing for Indian buyers since Apple hiked prices considerably for the iPhone 14 Pro models this year but it could spell good fortune for the standard models.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/17/1600x900/iPhone_14_Pro_Max_front_1665814810704_1673938229431_1673938229431.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.691586,
        "_id": "0bd69566efed699e940f8c584d33921f"
      },
      {
        "title": "Huge price cut now live! Don't pay 69900, grab iPhone 13 for just 40999",
        "author": "HT Tech",
        "published_date": "2023-01-17 07:34:45",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/huge-price-cut-now-live-don-t-pay-69900-grab-iphone-13-for-just-40999-71673940676199.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "Looking to buy an iPhone? Flipkart has an amazing offer live on the iPhone 13 where it can be yours for just Rs. 38999. Here's how.",
        "summary": "Looking to buy an iPhone? Flipkart has an amazing offer live on the iPhone 13 where it can be yours for just Rs. 38999. Here's how.\n If you've been searching the market for a new flagship smartphone, then the iPhone 13 deal is a must-look. The iPhone 13 is one of the best smartphones you can buy today. Despite being a year old, it stands at par with the best smartphones in the market. Although it is usually priced at a premium, Flipkart has announced a stellar deal on the smartphone and the price has taken a huge dip.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/17/1600x900/marcel-strauss-2an-BV9uzw0-unsplash_1664208815265_1673940813218_1673940813218.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.681982,
        "_id": "c984b8bbb04011ebbfade12b9e8c862d"
      },
      {
        "title": "iPhone Tricks: How To Remove Background From Photos In iOS 16",
        "author": "Tech Desk",
        "published_date": "2023-01-16 10:43:33",
        "published_date_precision": "full",
        "link": "https://www.news18.com/news/tech/iphone-tricks-how-to-remove-background-from-photos-in-ios-16-check-step-by-step-guide-6844111.html",
        "clean_url": "news18.com",
        "excerpt": "Thanks to iOS 16, You can remove the background from almost any image that has a relatively clear subject.",
        "summary": "Last year, Apple launched its latest operating system — iOS 16 with many interesting features including all-new personalised Lock Screens, Focus filters, Shared Photo Library, deleting a sent message, the ability to use emojis in the background image and removing the background from any image on iPhone.Thanks to iOS 16, You can remove the background from almost any image that has a relatively clear subject. With this feature, you can copy the subject and paste it into various apps, such as WhatsApp, iMessage, Instagram and more.",
        "rights": "news18.com",
        "rank": 2238,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Tech Desk",
        "media": "https://images.news18.com/ibnlive/uploads/2023/01/untitled-design-2023-01-12t151701.442-1-167386488116x9.jpg",
        "is_opinion": false,
        "twitter_account": "@cnnnews18",
        "_score": 12.638322,
        "_id": "4ca3b939464954c6d3d0d86b7a58d55a"
      },
      {
        "title": "Want iPhone 14 Pro Dynamic Island? Get it on any iPhone THIS way",
        "author": "HT Tech",
        "published_date": "2023-01-19 17:29:21",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/how-to/want-iphone-14-pro-dynamic-island-get-it-on-any-iphone-this-way-71674148803245.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "If you want the iPhone 14 Pro Dynamic Island on your iPhone, just get it this way.",
        "summary": "If you want the iPhone 14 Pro Dynamic Island on your iPhone, just get it this way.\n One of the most exciting and novel ideas of 2022 was the iPhone 14 Pro and iPhone 14 Pro Max Dynamic Island. Sadly, it is exclusively available with the top-end models of the iPhone 14 series. If you don't have an iPhone 14 Pro, but want to enjoy the versatility of the Dynamic Island on your iPhone, then don't fret! Here's an amazing trick to get Dynamic Island on any iPhone in a few simple steps. Whether you are using the standard iPhone 14, iPhone 13, iPhone 12, or any other model, this trick will bring the Dynamic Island to your device.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/19/1600x900/aditya-chinchure-mZA3_ytrnS8-unsplash_1674149252979_1674149275011_1674149275011.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.629404,
        "_id": "0fdaa90de58b17ba7d3c9d11771e254a"
      },
      {
        "title": "Flipkart Republic Day sale: Apple iPhone 12 Mini available at Rs 13,519 after Rs 25,480 discount, but there is a catch",
        "author": "DNA Web Team",
        "published_date": "2023-01-20 04:00:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.dnaindia.com/technology/report-flipkart-republic-day-sale-apple-iphone-12-mini-available-at-rs-13519-after-rs-25480-discount-3018138",
        "clean_url": "dnaindia.com",
        "excerpt": "Apple iPhone 12 Mini is a sound choice if you are planning to buy a feature-rich and easy to carry smartphone.",
        "summary": "Apple iPhone 12 MiniFlipkart Republic Day sale 2023 is ending today and it is the last day to buy the Apple iPhone 12 Mini at a huge discount. The Apple iPhone 12 Mini was the first Mini smartphone in Apple's portfolio. Although the smartphone belongs to the former flagship Apple iPhone series, it is still a desired phone for many buyers due to its small form factor and ease of use. The Apple iPhone 12 Mini was launched by the company in 2020 at a starting price of Rs 69,900. It was part of Apple iPhone 12 series that also comprises Apple iPhone 12, iPhone 12 Pro and iPhone 12 Pro Max.",
        "rights": "dnaindia.com",
        "rank": 2816,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "DNA Web Team",
        "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2023/01/20/2567507-apple-iphone-12-mini.png",
        "is_opinion": false,
        "twitter_account": "@dna",
        "_score": 12.625299,
        "_id": "57e2b690681af2f5d4cac2142fed2049"
      },
      {
        "title": "iPhone 15 Pro Max may feature folding lens camera",
        "author": "IANS",
        "published_date": "2023-01-19 04:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://zeenews.india.com/technology/iphone-15-pro-max-may-feature-folding-lens-camera-2563148.html",
        "clean_url": "india.com",
        "excerpt": "A folding zoom camera system is likely to not make a visible difference to the exterior of the iPhone, and will not necessarily reduce the camera bump.",
        "summary": "San Francisco: Apple's upcoming smartphone, iPhone 15 Pro Max, will reportedly feature a periscope folding zoom camera, although it will only be included in the top-end iPhone model. Earlier, the tech giant was expected to include a folding zoom camera system in the iPhone 14 range, reports AppleInsider. However, according to unspecified industry sources, major supplier of mobile camera modules LG Innotek and camera module parts maker Jahwa Electronics will both provide this system for the iPhone 15 Pro Max.",
        "rights": "india.com",
        "rank": 2337,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "IANS",
        "media": "https://english.cdn.zeenews.com/sites/default/files/2023/01/19/1143244-applecamera.jpg",
        "is_opinion": false,
        "twitter_account": "@zeenews",
        "_score": 12.588706,
        "_id": "430f0778e98042f845c193c2f2b41869"
      },
      {
        "title": "iPhone 12 Mini gets a huge discount! Grab it at just 16999 on Flipkart",
        "author": "HT Tech",
        "published_date": "2023-01-18 13:33:55",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/iphone-12-mini-gets-a-huge-discount-grab-it-at-just-16999-on-flipkart-71674047932442.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "Flipkart has a great offer on the iPhone 12 Mini right now and it can be yours for the price of a budget smartphone! Here's how.",
        "summary": "Flipkart has a great offer on the iPhone 12 Mini right now and it can be yours for the price of a budget smartphone! Here's how.\n Flipkart has come out with amazing deals on various smartphones, especially iPhones as part of its Big Savings Days Sale. Customers can take advantage of bumper discounts; bank offers and exchange offers which take down the price of smartphones hugely. There's an amazing offer live on the iPhone 12 Mini where it can be yours for the price of a budget smartphone! After applying all the offers, it can be yours for just Rs.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/18/1600x900/thai-nguyen-4f3fP9X5qYc-unsplash_1667996014545_1674048814598_1674048814598.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.535326,
        "_id": "820850aec513288b86e00ac04976dd69"
      },
      {
        "title": "Apple iPhone 15 Price Leaked: Here's How Much You May Have To Pay For The Upcoming Flagship",
        "author": "Ashish Singh",
        "published_date": "2023-01-17 11:45:56",
        "published_date_precision": "full",
        "link": "https://english.jagran.com/technology/apple-iphone-15-price-leaked-heres-how-much-you-may-have-to-pay-for-the-upcoming-flagship-10061501",
        "clean_url": "jagran.com",
        "excerpt": "According to reports the price of Apple s iPhone 15 series has been leaked The price difference between vanilla trims and Pro models will be 300",
        "summary": "By Ashish Singh\nTue, 17 Jan 2023 05:15 PM IST\n\n Minute Read \nAfter the launch of the iPhone 14 series, the upcoming iPhone 15 series have become the subject of leaks including the renders. In a recent report by Forbes, the alleged prices of the upcoming flagship have been leaked. With this, the report also suggested that there will be a massive difference in terms of price between the iPhone 15 and the iPhone 15 Pro. If the reports are accurate, the price of the new Apple iPhone 15 Pro models would be significantly higher than vanilla trims, while these vanilla trims might even experience a price decrease compared to the current generation iPhone 14 and iPhone 14 plus.",
        "rights": "jagran.com",
        "rank": 10496,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Ashish Singh",
        "media": "https://imgeng.jagran.com/images/2023/jan/Apple iPhone 15 Price Leak1673956261723.jpg",
        "is_opinion": false,
        "twitter_account": "@JagranEnglish",
        "_score": 12.497277,
        "_id": "b0275c3cfee4c6288dae62dcaf596c9e"
      },
      {
        "title": "More iPhones to be made in India, Apple eyes 50 percent of global production",
        "author": "HT Tech",
        "published_date": "2023-01-17 13:44:56",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/more-iphones-to-be-made-in-india-apple-eyes-50-percent-of-global-production-71673962775497.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "New report now suggests that Apple is eyeing to shift 50 percent of its global iPhone production to India by 2027.",
        "summary": "New report now suggests that Apple is eyeing to shift 50 percent of its global iPhone production to India by 2027.\n Apple makes a total 5 percent of its global iPhone supply in India at the moment and it was earlier said that the figure would go up to 25 percent by 2025. This alone indicated that Apple could focus on manufacturing all the standard variants of the iPhone in India by then. With talks of the Tata Group aiming to take over the Wistron plant in India, things are looking better for the Indian manufacturing scene.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/17/1600x900/IMG_5106_1666504626612_1673962932561_1673962932561.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.492512,
        "_id": "897b23334542c182207c4ded9fa190ee"
      },
      {
        "title": "iPhone 14 selling at a discount of Rs 12,000 on Apple Store: Here's how the deal works",
        "author": "Ankita Chakravarti",
        "published_date": "2023-01-19 00:00:00",
        "published_date_precision": "date",
        "link": "https://www.indiatoday.in/technology/news/story/iphone-14-selling-at-a-discount-of-rs-12000-on-apple-store-heres-how-the-deal-works-2323574-2023-01-19",
        "clean_url": "indiatoday.in",
        "excerpt": "The iPhone 14, which retails at Rs 79,900 for the 128GB variant, can be availed at a discount of up to Rs 7000 on Apple's online store.",
        "summary": "The iPhone 14, which retails at Rs 79,900 for the 128GB variant, can be availed at a discount of up to Rs 7000 on Apple's online store.By Ankita Chakravarti: Apple is offering an irresistible deal on the iPhone 14 series. The iPhone 14, which retails at Rs 79,900 for the 128GB variant, can be availed at a discount of up to Rs 7000 on Apple. In addition to that, you can get discounts of up to Rs 5000 if you exchange your old iPhone for the new one. Along with the iPhone 14, Apple is also offering discounts on other Apple products including iPad, Macbook and Apple Watch.",
        "rights": "indiatoday.in",
        "rank": 1817,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Ankita Chakravarti",
        "media": "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202301/iphone_14_image_1-sixteen_nine.jpg?VersionId=4cZIXAySCIApVa8IpILHHfzNDzrtmWoL",
        "is_opinion": false,
        "twitter_account": "@indiatoday",
        "_score": 12.476352,
        "_id": "c9c105afeda5cc318653d05ddccd7a7d"
      },
      {
        "title": "Only iPhone 15 Pro Max May Come With Periscope Camera Lens: What To Expect From Apple This Year",
        "author": "Tech Desk",
        "published_date": "2023-01-18 08:53:38",
        "published_date_precision": "full",
        "link": "https://www.news18.com/news/tech/only-iphone-15-pro-max-may-come-with-periscope-camera-lens-what-to-expect-from-apple-this-year-6859453.html",
        "clean_url": "news18.com",
        "excerpt": "Apple intends a 'Folded Zoom' periscope telephoto lens to be an exclusive feature in the iPhone 15 Pro Max this year.",
        "summary": "The US-based tech giant Apple is likely planning to bring the periscope camera lens system to the iPhone 15 Pro Max models only. According to a new report, the Pro Max variant will be the sole Apple smartphone of 2023 to get a periscope camera. A periscope lens offers optical zoom capabilities.Apple intends a ‘Folded Zoom' periscope telephoto lens to be an exclusive feature in the iPhone 15 Pro Max this year, The Elec, a South Korean publication, reported. The report corroborates the earlier predictions by the analyst Ming Chi-Kuo who had previously suggested that the periscope camera would remain exclusive to the bigger of the two Pro iPhone models this yearThe US-based tech giant is tapping new suppliers for the OIS actuators that will be used in the periscope lens destined for this year's iPhone 15 Pro Max.",
        "rights": "news18.com",
        "rank": 2238,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Tech Desk",
        "media": "https://images.news18.com/ibnlive/uploads/2023/01/iphone16pro-4-167402924616x9.jpg",
        "is_opinion": false,
        "twitter_account": "@cnnnews18",
        "_score": 12.473616,
        "_id": "01f53b6bda54c545f1165189dd19c597"
      },
      {
        "title": "Samsung Galaxy S23 will be great but it cannot dethrone iPhone 14",
        "author": "HT Tech",
        "published_date": "2023-01-20 14:52:43",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/samsung-galaxy-s23-will-be-great-but-it-cannot-dethrone-iphone-14-71674225426470.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "Samsung Galaxy S23 leaks suggest an impressive phone overall but the iPhone 14 could continue to outsell it. Here's why.",
        "summary": "Samsung Galaxy S23 leaks suggest an impressive phone overall but the iPhone 14 could continue to outsell it. Here's why.\n The Samsung Galaxy S23 series launch is just around the corner and based on the leaks so far, it seems that Samsung could have an impressive phone in its stable. The Galaxy S23 will use the newest Snapdragon 8 Gen 2 chip with a faster performance core, a triple rear camera, a 120Hz AMOLED display, and faster wired charging. For someone willing to spend a higher amount on a premium smartphone, this could be a great deal for many buyers.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/20/1600x900/thai-nguyen-98qe5sFlayc-unsplash_1669629023459_1674226023142_1674226023142.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.433947,
        "_id": "792da2df5d9d6fa0b3c72ccd11fd17e2"
      },
      {
        "title": "Apple Should Bring These Features to the iPhone 15",
        "author": "Lisa Eadicicco",
        "published_date": "2023-01-18 14:00:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.msn.com/en-us/news/technology/apple-should-bring-these-features-to-the-iphone-15/ar-AA13V2Ly",
        "clean_url": "msn.com",
        "excerpt": "Commentary: USB-C charging, Touch ID and more uses for the Dynamic Island are on my wish list.",
        "summary": "With the iPhone 14 Pro and Pro Max, Apple gave us many of the features we've been waiting for. These include an always-on display and better multitasking thanks to Apple's Dynamic Island. But there are a few ways Apple could take things further with the iPhone 15.\nFor example, the company could do a better job of bringing certain Pro-exclusive features down to its less-expensive iPhone models. Samsung frequently does this with its cheaper phones, and I'd like to see Apple embrace this approach more fully, too.",
        "rights": "msn.com",
        "rank": 100,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Lisa Eadicicco",
        "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA13c9uA.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 12.423754,
        "_id": "ca4a63d6ef226a9959ff79905fffe962"
      },
      {
        "title": "Flipkart vs Amazon: Apple iPhone 14 Pro Max at lowest price in Republic Day sale",
        "author": "DNA Web Team",
        "published_date": "2023-01-19 07:15:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.dnaindia.com/technology/report-flipkart-vs-amazon-apple-iphone-14-pro-max-at-lowest-price-in-republic-day-sale-3017942",
        "clean_url": "dnaindia.com",
        "excerpt": "The Apple iPhone 14 Pro Max is the first model that is powered by a A16 Bionic Chip and features a 48MP rear camera.",
        "summary": "Apple iPhone 14 Pro MaxFlipkart and Amazon Republic Day sales are ending tomorrow (January 20) and if you are planning to buy a new Apple iPhone 14 Pro Max, Apple AirPods or any other Apple product, this is the right time to go ahead. During the Republic Day, Flipkart and Amazon are offering amazing discounts on products across various categories including smartphones, earbuds and others. Apple's flagship iPhone model, Apple iPhone 14 Pro Max is usually sold out on both the platforms since it was launched last year but luckily, the smartphone is currently available on Flipkart and Amazon and that too with a huge discount.",
        "rights": "dnaindia.com",
        "rank": 2816,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "DNA Web Team",
        "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2023/01/19/2567338-apple-iphone-14-pro-max.png",
        "is_opinion": false,
        "twitter_account": "@dna",
        "_score": 12.422619,
        "_id": "313f41dea6b71793d7f458d9d2dc8032"
      },
      {
        "title": "Apple Sale: BIG DISCOUNTS on iPhones, iPads, MacBooks and more; Check special offers here",
        "author": "Zee Media Bureau",
        "published_date": "2023-01-19 13:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://zeenews.india.com/technology/apple-sale-big-discounts-on-iphones-ipads-macbooks-and-more-check-special-offers-here-2563460.html",
        "clean_url": "india.com",
        "excerpt": "Apple Sale: Apple is also offering a discount for music lovers, Airpods Pro Generation 2 is now available with a one-time discount of Rs 2,000, lowering the cost of the well-known earbuds to Rs…",
        "summary": "Apple a tech giant and one of the leading mobile brands in the world is offering huge discounted deals on variety of device including  iPhones, iPads, MacBooks, and more. Accessories such as Apple Watch bands and AirPods are also available at discounted prices. Customers can get up to Rs 10,000 discounts by taking advantage of Apple's instant savings offers on a variety of Apple products on the Apple Online Store. HDFC Bank credit card holders will get instant savings up to Rs 10,000 on selected products and can save up to Rs 12,000 when upgrading their existing iPhones.",
        "rights": "india.com",
        "rank": 2337,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Sagar Puri,Zee Media Bureau",
        "media": "https://english.cdn.zeenews.com/sites/default/files/2023/01/19/1143494-apples-big-sale.jpeg",
        "is_opinion": false,
        "twitter_account": "@zeenews",
        "_score": 12.416404,
        "_id": "ed3c040faf14f3ee738b0e8e7a29edc9"
      },
      {
        "title": "Apple agrees iPhone 14 Pro, iPhone 14 Pro Max have one more issue",
        "author": "HT Tech",
        "published_date": "2023-01-17 06:03:31",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/apple-agrees-iphone-14-pro-iphone-14-pro-max-have-one-more-issue-71673935221418.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "Apple confirms the green horizontal lines issue on iPhone 14 Pro, iPhone 14 Pro Max; says fix coming soon.",
        "summary": "Apple confirms the green horizontal lines issue on iPhone 14 Pro, iPhone 14 Pro Max; says fix coming soon.\n The iPhone 14 Pro and iPhone 14 Pro Max have been plagued with various bugs and issues ever since they went on sale. The initial rounds of buggy iOS 16 releases rendered the phones almost difficult to use. Although Apple has managed to fix most of the issues in the subsequent releases, the iPhone 14 Pro and iPhone 14 Pro Max are not exempt from issues that are hampering the user experience.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/17/1600x900/iPhone_14_Pro_Max_AOD_1663424222157_1673935328856_1673935328856.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.409695,
        "_id": "6881ad42447eace4e9ed753da259e2ff"
      },
      {
        "title": "Apple iPhone 15 Pricing Leaked",
        "author": "Adersh Unni Krishnan",
        "published_date": "2023-01-19 08:46:13",
        "published_date_precision": "full",
        "link": "https://techstory.in/apple-iphone-15-pricing-leaked-pro-models-to-get-a-price-hike/",
        "clean_url": "techstory.in",
        "excerpt": "Upcoming Apple iPhone 15 Pro models's pricing will get a never before hike, here is what we know:",
        "summary": "Apple iPhone 15 Pricing Leaked – Pro Models To Get A Price HikeImage Credits: Jason\nThe year 2023 will be the year when we will get to see the new iPhone series, which will be the iPhone 15 series. If you have been thinking about what this new iPhone 15 series will be featuring and what will be the launched pricing of the smartphone. Then, here we have got you covered with everything you need to know.\nAccording to a recent leak on the Apple iPhone 15 series, Weibo is a well-known source of information.",
        "rights": "techstory.in",
        "rank": 23310,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Adersh Unni Krishnan,Also,Bustle,God'S Own Country",
        "media": "https://techstory.in/wp-content/uploads/2023/01/Jason-1.jpg",
        "is_opinion": false,
        "twitter_account": "techstoryin",
        "_score": 12.400368,
        "_id": "3afc00251b85f18fc4a7578062439387"
      },
      {
        "title": "iPhone 14 selling at lowest price ever on Flipkart: Should you buy it?",
        "author": "Priya Pathak",
        "published_date": "2023-01-17 08:12:07",
        "published_date_precision": "full",
        "link": "https://www.financialexpress.com/life/technology-iphone-14-selling-at-lowest-price-ever-on-flipkart-should-you-buy-it-2950901/",
        "clean_url": "financialexpress.com",
        "excerpt": "iPhone 14 is selling at Rs 66,999 on Flipkart. This price does not include any bank offer or exchange offer.",
        "summary": "iPhone 14 is selling at its lowest price ever on Flipkart. The e-commerce giant is holding Flipkart Big Billion Days sale on its website wherein the company is selling iPhone 14 at a straight discount of Rs 10,000. The iPhone which sells at Rs 79, 900 on other days is currently available for buying at Rs 66,999 on Flipkart. To make the deal more lucrative, Flipkart is also giving a 10% off on Citi Bank and ICICI Bank card users. There's also an EMI plan available for the purchase. Further, there's up to Rs 22,000 off under the exchange offer.",
        "rights": "financialexpress.com",
        "rank": 2106,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Priya Pathak",
        "media": "https://www.financialexpress.com/wp-content/uploads/2023/01/iphone-14.webp",
        "is_opinion": false,
        "twitter_account": "@FinancialXpress",
        "_score": 12.397645,
        "_id": "e3d52e3e986b46ec23e157279b536109"
      },
      {
        "title": "iPhone 14 price drops to lowest ever! Buy it for 46999 instead 79900 of this way",
        "author": "HT Tech",
        "published_date": "2023-01-16 05:55:37",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/iphone-14-price-drops-to-lowest-ever-buy-it-for-46999-instead-79900-of-this-way-71673847680153.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "There's an amazing offer on the iPhone 14 live right now thanks to Flipkart's Big Saving Days Sale. Check out the offer details here.",
        "summary": "There's an amazing offer on the iPhone 14 live right now thanks to Flipkart's Big Saving Days Sale. Check out the offer details here.\n Flipkart's Big Savings Days Sale is live and buyers can grab smartphones, accessories, home appliances, clothing and more with huge discounts. Prices of smartphones have taken a huge plunge thanks to various deals introduced by Flipkart. One such offer is live on the iPhone 14, which is Apple's current flagship. The e-commerce platform is offering bank benefits and exchange offers in addition to discounted deals.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/16/1600x900/iphone_14_1662208330108_1673848484471_1673848484471.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.38171,
        "_id": "a60c8a865051009886b80a51bd508f5e"
      },
      {
        "title": "iPhone 11 discount! Grab iPhone at just 15999 on Flipkart this way",
        "author": "HT Tech",
        "published_date": "2023-01-18 06:35:37",
        "published_date_precision": "full",
        "link": "https://tech.hindustantimes.com/mobile/news/iphone-11-discount-grab-iphone-at-just-15999-on-flipkart-this-way-71674023580205.html",
        "clean_url": "hindustantimes.com",
        "excerpt": "There's a hot deal live on the iPhone 11 by Flipkart. Know the full discount details here.",
        "summary": "There's a hot deal live on the iPhone 11 by Flipkart. Know the full discount details here.\n The iPhone 11 was launched in 2019 and became an instantaneous hit. In fact, it became the best-selling smartphone globally for two consecutive years. Apple shipped nearly 65 million units of the iPhone 11 in 2020 alone. Although it is quite a few years old now, it can still hold up against today's smartphones. If you're looking for a smartphone which offers good performance at a not-so-premium price, the iPhone 11 could be one of the best options in the market.",
        "rights": "hindustantimes.com",
        "rank": 980,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "HT Tech",
        "media": "https://images.hindustantimes.com/tech/img/2023/01/18/1600x900/v-a-tao-HBp6rDjh5ew-unsplash_1671372741685_1674023676836_1674023676836.jpg",
        "is_opinion": false,
        "twitter_account": "@HTTech",
        "_score": 12.3774395,
        "_id": "b211f7e89a5c3d28f4788ff0918748df"
      },
      {
        "title": "iPhone 14 down to its lowest price ever since launch on Flipkart,grab the deal while it lasts",
        "author": "Ankita Chakravarti",
        "published_date": "2023-01-17 03:50:01",
        "published_date_precision": "full",
        "link": "https://www.indiatoday.in/technology/news/story/iphone-14-down-to-its-lowest-price-ever-since-launch-on-flipkartgrab-the-deal-while-it-lasts-2322482-2023-01-17",
        "clean_url": "indiatoday.in",
        "excerpt": "iPhone 14 has received a major price cut ever since its launch. The device is being sold at a discount of Rs 10,000 on Flipkart.",
        "summary": "For the first time since its launch, the Apple iPhone 14 has received a price cut. The smartphone has received a price cut of Rs 2500 on Flipkart. Interestingly, the iPhone 14 was launched at Rs 79,900 in September this year. However, the device is now listed at Rs 77,400 on Flipkart. This price is not inclusive of any bank offer or exchange offer. However, if you have an old smartphone to trade in and an HDFC bank card, you can get the device for less than Rs 60,000.\nHere is how the deal works The iPhone 14 is listed at Rs 77,400 on Flipkart, this is the lowest the device has been priced ever since its launch.",
        "rights": "businesstoday.in",
        "rank": 1817,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Ankita Chakravarti",
        "media": "https://akm-img-a-in.tosshub.com/businesstoday/images/story/202301/iphone_14_image_0-sixteen_nine-original.jpg",
        "is_opinion": false,
        "twitter_account": "@business_today",
        "_score": 12.368791,
        "_id": "59f469d884f5db639576d49c4d94899b"
      },
      {
        "title": "iPhone 14 down to its lowest price ever since launch on Flipkart, here's how you can grab the deal",
        "author": "Ankita Chakravarti",
        "published_date": "2023-01-17 00:00:00",
        "published_date_precision": "date",
        "link": "https://www.indiatoday.in/technology/news/story/iphone-14-down-to-its-lowest-price-ever-since-launch-on-flipkartgrab-the-deal-while-it-lasts-2322482-2023-01-17",
        "clean_url": "indiatoday.in",
        "excerpt": "iPhone 14 has received a major price cut ever since its launch. The device is being sold at a discount of Rs 10,000 on Flipkart.",
        "summary": "iPhone 14 has received a major price cut ever since its launch. The device is being sold at a discount of Rs 10,000 on Flipkart.By Ankita Chakravarti: If you have been planning to buy the iPhone 14 but could not do so because of its expensive price tag, now is the time to do so. That is because the iPhone 14 is down to its lowest ever price since its launch. The iPhone 14, which was originally priced at Rs 79,900, is listed at Rs 66,900. The price of the phone has been lowered because of the ongoing Flipkart Big Saving Days sale.",
        "rights": "indiatoday.in",
        "rank": 1817,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "Ankita Chakravarti",
        "media": "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202301/iphone_14_image_0-sixteen_nine.jpg?VersionId=YIXdY7XFNFS5g0m3ixrwfyP99flDL7CV",
        "is_opinion": false,
        "twitter_account": "@indiatoday",
        "_score": 12.365518,
        "_id": "9946fbfa093ec560c47d70f54f2e7201"
      },
      {
        "title": "How to change the font on your iPhone",
        "author": "Kurt Knutsson",
        "published_date": "2023-01-19 14:48:28",
        "published_date_precision": "full",
        "link": "https://www.foxnews.com/tech/how-change-font-your-iphone",
        "clean_url": "foxnews.com",
        "excerpt": "Kurt \"CyberGuy\" Knutsson explains step-by-step how to change your iPhone's font size and font style if you have trouble reading your screen.",
        "summary": "Every iPhone model comes with the same font size and style. However, some people may have trouble reading their screens because the font is so small, while others may wish to have a different font. There is a way to switch things up on your iPhone screen, and we'll teach you how.CLICK TO GET KURT'S CYBERGUY NEWSLETTER WITH QUICK TIPS, TECH REVIEWS, SECURITY ALERTS AND EASY HOW-TO'S TO MAKE YOU SMARTERHow to change the font size on your iPhoneIf you're someone who struggles to read the small letters on your iPhone screen, follow these steps to make your font a bigger size:Open your Settings appTap Accessibility  Go here to change the font size on your iPhone.",
        "rights": "foxnews.com",
        "rank": 249,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Kurt Knutsson",
        "media": "https://static.foxnews.com/foxnews.com/content/uploads/2023/01/5-FONTS-APP.jpg",
        "is_opinion": false,
        "twitter_account": "@foxnews",
        "_score": 12.349955,
        "_id": "dd7b4976ac095a7f9007dddc01c10d99"
      },
      {
        "title": "[Latest information in 2023]How to reset iPhone to factory default[PassFab iPhone Unlock]",
        "author": "World Today News",
        "published_date": "2023-01-17 01:35:14",
        "published_date_precision": "full",
        "link": "https://www.world-today-news.com/latest-information-in-2023how-to-reset-iphone-to-factory-defaultpassfab-iphone-unlock-press-release-of-passfab-co-ltd/",
        "clean_url": "world-today-news.com",
        "excerpt": "In addition to fixing iPhone problems, preventing misuse when lost, deleting data when transferring or selling, and resetting the iPhone as a new device when the screen lock passcode is forgotten, the…",
        "summary": "In addition to fixing iPhone problems, preventing misuse when lost, deleting data when transferring or selling, and resetting the iPhone as a new device when the screen lock passcode is forgotten, the factory resets the iPhone. It may be necessary to restore (initialize) the factory settings. However, since it is not an operation that is performed on a daily basis, I think that it may take some time when a quick response is required. In this article4 Ways to Factory Reset iPhoneWe will introduce you, so please refer to it so that you can respond smoothly according to the situation.",
        "rights": "world-today-news.com",
        "rank": 38139,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "World Today News",
        "media": "https://prtimes.jp/i/98839/182/ogp/d98839-182-77aa653f3969913df002-0.png",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 12.349905,
        "_id": "a481d8f24d422f4ae42776f412b528d1"
      },
      {
        "title": "iPhone 15 Series Price Leak Might Worry Those Wanting the Pro Models!",
        "author": "Vanshika Malhotra",
        "published_date": "2023-01-18 12:16:36",
        "published_date_precision": "full",
        "link": "https://beebom.com/iphone-15-series-price-leaked/",
        "clean_url": "beebom.com",
        "excerpt": "iPhone 15 series will launch this year and ahead of the launch, we now we have the leaked prices with us. Check out the details right here!",
        "summary": "Apple will be launching the new iPhone 15 series this year and before this officially happens, there's a lot that has leaked. Joining this list of rumors, we now have the leaked pricing of the upcoming iPhone 15 phones and this might be more for the Pro models. Here's what could be! iPhone 15 Price Leaked A recent post on Weibo suggested that Apple will increase the prices of the iPhone 15 Pro models. This will be a part of its strategy to maintain a price gap between the standard and the Pro variants of the lot.",
        "rights": "beebom.com",
        "rank": 12721,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "Vanshika Malhotra",
        "media": "https://beebom.com/wp-content/uploads/2023/01/iphone-14-plus-photo.jpg",
        "is_opinion": false,
        "twitter_account": "@BeebomCo",
        "_score": 12.332194,
        "_id": "34a1cfa3f77371d51c77e4e60ef12aa9"
      },
      {
        "title": "Latest Android news may convince millions to switch to Apple's iPhone",
        "author": "David Snelling",
        "published_date": "2023-01-16 08:34:00",
        "published_date_precision": "full",
        "link": "https://www.express.co.uk/life-style/science-technology/1721725/Android-Galaxy-Google-trade-in-value-Apple-iPhone",
        "clean_url": "express.co.uk",
        "excerpt": "Android phone owners hit by a massive drop in the value of their devices whilst Apple's iPhone continues to buck this trend.",
        "summary": "Android v iPhone (Image: GETTY • APPLE)Anyone hoping to sell their current smartphone and trade up for something new this year might be in for a shock. An in-depth new report from US firm SellCell has revealed the worst devices for depreciation and Android is, once again, falling way behind when compared to the iPhone. In fact, all of the top 10 phones that have lost the least amount of value since launch come from Apple with all dropping by less than 40 percent.That's compared to many Android devices which are now worth up to 80 percent less than when they were initially released.",
        "rights": "express.co.uk",
        "rank": 555,
        "topic": "tech",
        "country": "GB",
        "language": "en",
        "authors": "David Snelling",
        "media": "https://cdn.images.express.co.uk/img/dynamic/59/1200x712/4509091.jpg?r=1673858875379",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 12.3216915,
        "_id": "2f395744ef752997ff145c6715ad6f94"
      },
      {
        "title": "Suggested new Forum category for iPhone",
        "author": "FreakinEurekan",
        "published_date": "2023-01-19 23:51:47",
        "published_date_precision": "full",
        "link": "https://forums.macrumors.com/threads/suggested-new-forum-category-for-iphone.2377583/",
        "clean_url": "macrumors.com",
        "excerpt": "The iPhone section in Forums has three sections - 'iPhone,' 'iPhone Tips, Help, and Troubleshooting,' and 'iPhone Accessories.' I'd like to suggest adding a separate section for 'iPhone Cases, Covers,…",
        "summary": "Sep 8, 2011\n\n\n\n\n\n\n\n4,074\n\n\n\n\n\n\n\n1,131\n\n\n\n\n\n\n\n\nEureka Springs, Arkansas\n\n\n\n \n\n\n\n\n\n \n\n\n\nThe iPhone section in Forums has three sections - 'iPhone,' 'iPhone Tips, Help, and Troubleshooting,' and 'iPhone Accessories.' I'd like to suggest adding a separate section for 'iPhone Cases, Covers, and Protectors' - currently the Accessories section is INUNDATED with case/cover/screen protector posts, to the point that it's hard for anything else to get traction.",
        "rights": "macrumors.com",
        "rank": 1201,
        "topic": "tech",
        "country": "US",
        "language": "en",
        "authors": "FreakinEurekan",
        "media": "https://images.macrumors.com/social/?t=2377583&v=6",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 12.230739,
        "_id": "8dcacbb52d56d35e13bd46b4f434734f"
      },
      {
        "title": "iPhone 14 gets flat Rs 12,901 discount during Flipkart Big Saving Days sale, but is it worth buying?",
        "author": "BusinessToday.In",
        "published_date": "2023-01-15 10:48:42",
        "published_date_precision": "full",
        "link": "https://www.indiatoday.in/technology/news/story/iphone-14-gets-flat-rs-12901-discount-during-flipkart-big-saving-days-sale-but-is-it-worth-buying-2321842-2023-01-15",
        "clean_url": "indiatoday.in",
        "excerpt": "The iPhone 14 is listed on Flipkart with a starting price of Rs 66,999. Flipkart is currently selling the iPhone 13 with a starting price of Rs 59,499.",
        "summary": "Story highlights Flipkart is offering big discounts on iPhones during Big Saving Days sale. The iPhone 14 is listed on Flipkart with a starting price of Rs 66,999. Flipkart is currently selling the iPhone 13 with a starting price of Rs 59,499. Flipkart is hosting a Republic Day sale on its platform and is calling Big Saving Days sale. The sale went live earlier today and will continue until January 20. The e-commerce giant is offering pretty enticing deals on several 5G phones in India. People who have been waiting to buy iPhones at a discounted rate probably shouldn't miss this sale event.",
        "rights": "businesstoday.in",
        "rank": 1817,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "BusinessToday.In",
        "media": "https://akm-img-a-in.tosshub.com/businesstoday/images/story/202301/iphone_13_pixabay-sixteen_nine-original.jpg",
        "is_opinion": false,
        "twitter_account": "@business_today",
        "_score": 12.200522,
        "_id": "554ee63d0a86f69f90dacb2006f07bd1"
      },
      {
        "title": "Amazon and Flipkart Republic Day Sale: Apple iPhone 14 Pro Max available at huge discount, check out the deal here",
        "author": "DNA Web Team",
        "published_date": "2023-01-19 11:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.dnaindia.com/technology/report-amazon-and-flipkart-republic-day-sale-apple-iphone-14-pro-max-available-at-huge-discount-check-out-the-deal-3018003",
        "clean_url": "dnaindia.com",
        "excerpt": "During the Republic Day sale, both Flipkart and Amazon are offering discounts on various products. Apple iPhone 14 Pro Max, Apple AirPods, etc.",
        "summary": "File PhotoFlipkart and Amazon are currently running a Republic Day sale which is all set to end tomorrow - January 20, 2023. If you are looking to buy a new Apple iPhone 14 Pro Max, Apple AirPods, or any other Apple product, this sale is an opportunity for you to do it.  During the Republic Day sale, both Flipkart and Amazon are offering discounts on various products. Apple iPhone 14 Pro Max, and Apple AirPods are available at a reduced rate on both Amazon and Flipkart.  For those who are unaware, the Apple iPhone 14 Pro Max was initially priced at Rs 1,39,900.",
        "rights": "dnaindia.com",
        "rank": 2816,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "DNA Web Team",
        "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2023/01/19/2567390-image-2.png",
        "is_opinion": false,
        "twitter_account": "@dna",
        "_score": 12.165735,
        "_id": "231f3207579b5f431a6aea03727e8b03"
      },
      {
        "title": "India or Vietnam may soon become biggest Apple iPhone manufacturer",
        "author": "DNA Web Team",
        "published_date": "2023-01-15 09:00:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.dnaindia.com/technology/report-india-or-vietnam-may-soon-become-biggest-apple-iphone-manufacturer-3017205",
        "clean_url": "dnaindia.com",
        "excerpt": "Apple is eyeing to ramp up manufacturing in India amid Covid-related supply chain issues in China.",
        "summary": "Apple (Image: Reuters)China, which is still the key Apple supplier, may lose its tag as leading iPhone manufacturer as Apple looks at India and Vietnam to bolster its supply chain, the media reported on Saturday. Largest Apple supplier Foxconn has \"quietly finalised plans\" to relocate some of its Apple iPad and MacBook production to Vietnam, reports The South China Morning Post. Apple has reportedly cut back on orders citing weakening demand in potential blow to its Chinese suppliers amid Covid disruptions.",
        "rights": "dnaindia.com",
        "rank": 2816,
        "topic": "tech",
        "country": "IN",
        "language": "en",
        "authors": "DNA Web Team",
        "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2023/01/15/2566664-apple.png",
        "is_opinion": false,
        "twitter_account": "@dna",
        "_score": 12.148702,
        "_id": "ef53d566533662e5e9d8d76dfd77558a"
      }
    ])
    console.log(data)
  return (
   <View >
                  <StatusBar barStyle="light-content" />
   <ScrollView style={{marginTop:15}}>
    {data.map((data)=>{
       return(
        <View style={{justifyContent:'center',alignItems:'center'}}>
          <TouchableOpacity onPress={()=>navigation.navigate('ArticleScreen',{data:data})}>
          <NewsItem key={data._id} data={data}/>
          </TouchableOpacity>
            </View>
       )
  })}
   </ScrollView>
   </View>
  )
}
